hl.curve("easeOutCirc", { type = "bezier", points = { { 0, 0.55 }, { 0.45, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0 }, { 0.35, 1 } } })
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "easeOutExpo", style = "popin 50%" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "easeOutExpo", style = "slidefade 5%" })
hl.animation({ leaf = "border", enabled = true, speed = 3.5, bezier = "easeInOutCubic" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.5, bezier = "easeOutExpo" })
hl.animation({ leaf = "fade", enabled = true, speed = 5, bezier = "easeOutExpo" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 6, bezier = "easeOutQuint", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 6, bezier = "easeOutQuint", style = "popin 85%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 2, bezier = "easeInOutCubic" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2, bezier = "easeOutQuint" })
