hl.on("hyprland.start", function()
	hl.exec_cmd("waypaper --restore")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("waybar")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY _CURRENT_DESKTOP")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("udiskie &")
	hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME")
end)
