#!/bin/bash

CONFIG_LOC="/home/larry/.config/waybar/config.jsonc /home/larry/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
  waybar & 
  inotifywait -e create,modify $CONFIG_LOC
  killall waybar
done